# Generated by Django 4.1.7 on 2023-03-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_question_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_true_answer',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
