# Generated by Django 4.1.7 on 2023-03-07 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_question_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
