# Generated by Django 4.1.7 on 2023-03-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_question_favourites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='likes',
            new_name='likes_count',
        ),
    ]
